---
- name: install/uninstall s/w.s apps
  hosts: all
  vars:
        a: tomcat9
        b: present
        c: yes
  tasks: 
   - name: install/unistall 
     apt:
       name: "{{a}}"
       state: "{{b}}"
       update_cache: "{{c}}"
...

