---
- name: install fire wall using host scope vairable
  hosts: webserver
  tasks:
    - name:  install firewalld
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
